#!/usr/bin/env node
"use strict";

var express     = require('express'),
    path        = require('path');
var logger     = require("morgan");

var staticDirs = ['lib','css', 'js', 'lib', 'partials', 'styles', 'templates', 'assets'],
    app = express();

app.use(logger('dev'));

app.configure(function () {
  staticDirs.forEach(function (item) {
    app.use('/'+item, express['static']('app/'+item));
  });
});


app.all("*", function(req, res, next) {
    res.sendfile(path.join(__dirname, 'app/index.html'));
  //fs.createReadStream('app/index.html').pipe(res);
});

console.log('Listening on Port 1970');
app.listen(1970);