#!/usr/bin/env node
"use strict";

var express     = require('express'),
    path        = require('path');

var staticDirs = ['lib','css', 'js', 'partials'],
    app = express();

app.configure(function () {
    staticDirs.forEach(function (item) {
        app.use('/'+item, express['static']('app/'+item));
    });
});

app.all("*", function(req, res, next) {
    res.sendfile(path.join(__dirname, 'app/index.html'));
});

console.log('Listening on Port 1970');
app.listen(1970);