#!/usr/bin/env node

"use strict";

var express     = require('express'),
    fs          = require('fs'),
    staticDir   = express['static'],
    path        = require('path'),
    _          = require('underscore');

var staticDirs = ['css','lib', 'data'],
    PATH = path.join(__dirname, 'app/examples'),
    app = express();

app.use(express.directory(PATH, {icons:true}));
app.use(express.static(PATH));

app.configure(function () {
  staticDirs.forEach(function (item) {
    app.use('/'+item, express.static(path.join(__dirname, 'app/'+item)));
  });
  app.use(express.bodyParser());
});

app.get("/data/cache", function (req, res) {
  var pathx = path.join(__dirname, 'app/data/cache.json');
  var arr = JSON.parse(fs.readFileSync(pathx, 'utf8'));
  res.json(arr);
  res.end();
});

app.get("/someurl", function (req, res) {
  res.json({"link" : "http://nicklowman.co.uk"});
  res.end();
});

app.post("/twitter", function (req, res) {
  res.json(req.body);
  res.end();
});


app.post("/forms", function (req, res) {
  var b = req.body;

  if (!b.name || !b.superheroAlias) {
    b.message = 'The request is bad';
    b.success = false;
    b.errors = {};

    if (!b.name)
      b.errors.name = 'Missing name';

    if (!b.superheroAlias)
      b.errors.superheroAlias = 'Fill out superher sucker!';

  } else {
    b.message = 'The request is good';
    b.success = true;
  }

  res.json(b);
  res.end();
});


console.log('Listening on Port 1970');
console.log(PATH);
app.listen(1970);